### ISSUE TITLE
Can't download Sonic Pi for Windows 2.5.0

### ISSUE THREAD

**Issue by hopbit** [samaaron/sonic-pi-web#4]
Hi there,

I've just wanted to check out some new features that are available in latest version of Sonic Pi. Currently I'm using Sonic Pi for Windows 2.3.0.

Unfortunatelly I can't download latest version of Win Installer which should be available under [this localization](http://sonic-pi.net/files/releases/02.5.0/Sonic-Pi-for-Win-v2.5.0.msi). After clicking on download button I'm waiting, waiting and... waiting.

I don't know if this problem occur only for me, but I've created temporary workaround - downloads mirror placed on Google Drive. The patch is available [here](https://github.com/hopbit/sonic-pi-web/commit/1454193d2b026569893f5485e6a7932d074bb152). I've placed it under feature branch [here](https://github.com/hopbit/sonic-pi-web/tree/sonic-pi-for-windows-download-mirror).

Regards, 
Luke.

**Comment by hopbit** [comment]
OK. Now it's available. I downloaded it, installed it, and placed it under the mirror mentioned above. The problem seems not exist anymore, but I think, that creating a mirror should be a nice option.

**Comment by claremacrae** [comment]
I'd suggest closing this issue - downloads now currently work, and download mirrors would be a separate feature, so no more work is needed here.

**Comment by hopbit** [comment]
OK.
